# Generated by Django 5.0.1 on 2024-02-07 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicPlayer', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='audio_link',
        ),
    ]
